# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9e17b3c17d78242541a929c9b3d3bc6b"
name = "Customer Approval"
application_url = "https://xm-club-customer-approval.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xmclub-psw9jzce.myshopify.com"

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_customers,read_metaobject_definitions,read_metaobjects,read_products,write_customers,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://xm-club-customer-approval.vercel.app/auth/callback",
  "https://xm-club-customer-approval.vercel.app/auth/shopify/callback",
  "https://xm-club-customer-approval.vercel.app/api/auth/callback"
]

[app_proxy]
url = "/api/proxy"
subpath = "customer-approval"
prefix = "apps"
